### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by wiisafetymanual** [corgi-in-tights/wherearemytms#1]
It literally didn't add anything to the game

**Comment by corgi-in-tights** [comment]
cool

**Comment by corgi-in-tights** [comment]
are you using forge, can you send your setup details (modpack, version, etc.)

**Comment by corgi-in-tights** [comment]
please leave a 5 star review if this fixed your issue

**Comment by corgi-in-tights** [comment]
charisma mustv fixed issue
